services:
  db:
    image: mysql:latest
    container_name: forohub-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forohub
      MYSQL_USER : forohub
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: